### ISSUE TITLE
Feature request: Middleware decorator on class

### ISSUE THREAD

**Issue by richjyoung** [seanpmaxwell/overnight#10]
I would like to be able to apply the same middleware to all routes on a router instance, rather than have to specify the same middleware annotation on each route. In traditional Express applications this would be a `router.use(middleware);` statement.

Unless I've missed a way to do this, could this be achieved by allowing the Middleware annotation on the controller class?

Overnight is an excellent library and truly a pleasure to use, thank you!

**Comment by seanpmaxwell** [comment]
I'll create this feature and let you know when I do

**Comment by seanpmaxwell** [comment]
Your feature request has been fulfilled. Please star the repo if you have not done so yet :)

**Comment by richjyoung** [comment]
So I've tried it and it does add middleware to the class router, however regular route middleware decorators have now stopped working.  I've had a look through your changes and can't spot why this would be the case.

My environment adds a single middleware function to the class, and an array of express-validator middleware to the route, and the route middleware does not take effect at all.

At the moment I have to pin my version to 1.5.2 so if you could keep me updated that would be great.

**Comment by seanpmaxwell** [comment]
Yes there is a slight bug in that version. Sorry about that. Make sure you update to the latest 1.5.3.

**Comment by richjyoung** [comment]
Sorry I meant I have to pin it to 1.5.2 so the regular middleware decorator works. 1.5.3 has the issue I described where the route middleware (@Middleware(...)) does not get called.

**Comment by seanpmaxwell** [comment]
Hey thanks so much for pointing that out. There was a bug in the Server.ts file. When I changed the middleware key for routes from 'middleware' to 'routeMiddleware' I didn't update it in the server and that's what caused the bug. 1.5.4 should have the fix now.

**Comment by richjyoung** [comment]
That's great, thanks. Works as expected now.
