### ISSUE TITLE
Question: Do you plan supporting Swagger/OpenAPI?

### ISSUE THREAD

**Issue by francisbrito** [seanpmaxwell/overnight#11]
Hello,

Firstly, I'd like to 👏 at you for building this library. I've been looking for a nice library to allow me to decorate express middleware without putting much effort into it. This library is just that.

Secondly, I'd like to ask, is there any plans on supporting OpenAPI/Swagger generation? As a backend developer, I'm asked to provide this documentation frequently and sometimes keeping it up to date with the ever-changing requirements can be daunting. I'd love to be able to use this tool to help me out with that.

What are your thoughts?

**Comment by seanpmaxwell** [comment]
I believe Swagger is just a middleware for Express so OvernightJS wouldn't have any impact on how you use it. Just use the `@Middleware` decorator like you would any other middleware.
