### ISSUE TITLE
Support for HTTP PATCH

### ISSUE THREAD

**Issue by AnandChowdhary** [seanpmaxwell/overnight#13]
Currently, only the following HTTP verbs are available to import from `@overnightjs/core`:

- GET
- POST
- DELETE
- PUT

PATCH should be added as well.

**Comment by AnandChowdhary** [comment]
For that matter, all Express.js verbs should be supported. The list is available here: https://expressjs.com/en/api.html#routing-methods

**Comment by AnandChowdhary** [comment]
The pull request has been updated with support for all Express.js verbs.

**Comment by seanpmaxwell** [comment]
I merged your changes in the master branch. Overnight should support all Express routes now.
