### ISSUE TITLE
Support for path aliases

### ISSUE THREAD

**Issue by AnandChowdhary** [seanpmaxwell/overnight#16]
Can we have support for multiple paths (aliased) which, perhaps something like this:

```ts
@Controller("user")
export class UserController {
  @Get("info", "example")
  get userInfo(req: Request, res: Response) {
    res.json({ user: "hello" });
  }
}
```

Using multiple attributes in the `@Get()` decorator, we can have aliased routes:

- GET /user/info
- GET /user/example

Both result in the `userInfo()` function being called.

**Comment by AnandChowdhary** [comment]
Alternately, we can have an additional decorator:

```ts
@Controller("user")
export class UserController {
  @Get("info")
  @Alias("example")
  @Alias("another-example")
  get userInfo(req: Request, res: Response) {
    res.json({ user: "hello" });
  }
}
```

**Comment by seanpmaxwell** [comment]
I think the best way to do it would be to have the decorator pass a string or string[]. But what about this, wouldn't it be easier (for other devs who read your code) just to create a shared private method, and call it in both the class members decorated with @Get('info') and in @Get('example')?

**Comment by AnandChowdhary** [comment]
I think you can definitely create private methods, but in my case it would just become a bit messier. I think allowing an array of strings in `@Get` decorators can still be added as a feature, I think it would be super useful. 😄

```ts
@Get(["hello", "world"])
```

If you're busy, I can make a pull request too. 😉

**Comment by seanpmaxwell** [comment]
Go ahead and make the pull-request. I'll look it over when I have time. As part of the pull request, if you could make a new controller for the sample-project/ called MultiRoutePracticeController or something like that, it would be helpful.
