### ISSUE TITLE
Examples with passport

### ISSUE THREAD

**Issue by EvanBurbidge** [seanpmaxwell/overnight#2]
Cool work on this, looking forward to messing about with it, I see there is support built in for using JWT is it almost the same approach when using passport for authentication. Would it just be passed into the method via the @Middleware decorator. 

Would be nice to see some more examples with middleware for auth, maybe some mongodb integrations?

**Comment by seanpmaxwell** [comment]
I think this is what you are looking for: https://github.com/seanpmaxwell/overnight/blob/master/sample-project/src/controllers/JwtPracticeController.ts. There are quite a few examples in the sample project. As far as Mongo integration goes. It wouldn't really change the way you interact with mongo. What I would do is create a separate DAO (data-access-object) class, put my mongo queries in there, return a promise, then call those methods in my controller.

**Comment by seanpmaxwell** [comment]
If you need to use multiple middleware's you can pass them as an array:

```
@Get('/protected')
@Middleware([checkToken, checkMethod])
method...
```

**Comment by EvanBurbidge** [comment]
Awesome! Thanks for the insights! looking forward to getting stuck into this! :)
