### ISSUE TITLE
Enviroment Proposal

### ISSUE THREAD

**Issue by jeremiassantos** [seanpmaxwell/overnight#27]
Hello, we are using a lot overnight and it is fantastic, we miss a more sophisticated environment management, I have a library that does environment management (https://www.npmjs.com/package/roit-environment) is Possible agent to partner and incorporate this management into the overnight?

**Comment by seanpmaxwell** [comment]
Hmm, what's wrong with using dotenv? That's what I use and it's pretty easy, straightforward.

**Comment by jeremiassantos** [comment]
Here in our work, we had some limitations with `dotenv`, mainly in controlling different environments, we could find this model with roit-environment, which is very simple to configure, and standardizes the management of the environment, besides having the ease of annotation of the .yaml file, finally, I understand that it can add a lot.

**Comment by seanpmaxwell** [comment]
I use an extremely small/simple index.js script in an env/ folder. Just -r the the folder and pass in an argument. You can see an example of it here, https://github.com/seanpmaxwell/InHouseDbMigrationHandler/blob/master/env/index.js. Sorry I know I'm being stubborn but seems a lot easier than creating a whole new module.

**Comment by jeremiassantos** [comment]
Thanks for listening, in our applications we will continue to use the combination of overnight + roit-enviroment, which is working very well!
