### ISSUE TITLE
Custom Middleware Implementation

### ISSUE THREAD

**Issue by proletesseract** [seanpmaxwell/overnight#28]
Hey Sean, first of all thanks for this framework. I use it in a few of my API projects so far and it awesome! It's not really an issue, but more of a question.

I'm still struggling to get my head around how to implement custom Middleware using the decorator. For example, i can write this simple express app level middleware;

**auth.middleware.js**
```
import { Request , Response, NextFunction } from 'express'

export class AuthMiddleware {

  constructor() {
    console.log('AuthMiddleware')
  }

  public verifyAuth(req:Request, res:Response, next:NextFunction) {
    console.log('verifyAuth')
    // do stuff to verify the user should be able to access this route
    // could be JWT token auth, could be ACL database lookups, could be IP validation etc..
    next()
  }
}
```
And call it in the server constructor at an app level;
```
...

class ExampleServer extends Server {

  private authMiddleware = new AuthMiddleware()

  constructor() {
      super(true);
      this.app.use(bodyParser.json({limit: '50mb'}));
      this.app.use(bodyParser.urlencoded({extended: true}));
      this.app.use(this.authMiddleware.verifyAuth) // Here is the middleware
      this.setupControllers();
  }
}
...
```
Which works fine, but ideally i would be able to do something similar using the `@Middleware` decorator from within my API Controller file so i can decide which routes are effected;
```
...
@Controller('api/v1/generate')
export class MyController {

  private authMiddleware = new AuthMiddleware()

  constructor() { }

  @Get('middleware-test')
  @Middleware(authMiddleware.verifyAuth)
  protected test(req: Request, res: Response, next:NextFunction) {
    return res.status(200).json({
      message: 'OK'
    })
  }
}
...
```
Of course this doesn't work because the Middleware decorator is expecting the type RequestHandler to be returned. I'm not exactly sure whether what I'm trying to do is possible or practical or if there's a better way to do it. I've tried looking at how you implemented the JwtHandler to see if i can replicate that with my own middleware but to no success. 

Any thoughts appreciated.

**Comment by seanpmaxwell** [comment]
I do have a an example of using custom middleware in this controller for the sample project:
_https://github.com/seanpmaxwell/overnight/blob/master/sample-project/src/controllers/ClassDecoratorController.ts_

Here's the file where I create the custom middleware:
_https://github.com/seanpmaxwell/overnight/blob/master/sample-project/src/controllers/other/CustomMiddleware.ts_

**Comment by proletesseract** [comment]
Ah okay, thanks for pointing me there. Looks simple enough, i will give it a try :)

**Comment by proletesseract** [comment]
Works like a dream, thanks for that!
