### ISSUE TITLE
base url pathname

### ISSUE THREAD

**Issue by artoodeeto** [seanpmaxwell/overnight#30]
Hello. I really like what you did here. so simple, easy to understand. Question though. I have controllers that has a basepath of `api/v1` is there a way to add this into the setup of controllers on the server class rather than each controller? thank you.

**Comment by seanpmaxwell** [comment]
I would make a parent controller and use api/v1 as it's route

**Comment by artoodeeto** [comment]
I did but I got an error. `TypeError: core_1.ChildControllers is not a function` theres no ChildControllers class?

**Comment by artoodeeto** [comment]
I checked the code I think you renamed it `Children` not `ChildrenControllers`

**Comment by seanpmaxwell** [comment]
Oh yeah you're right. I need to update the readme. There's an example here.
https://github.com/seanpmaxwell/overnight/blob/master/sample-project/src/controllers/nesting/ParentController.ts

**Comment by artoodeeto** [comment]
yea i got it already. I dig into the code. thanks for this. :) if you want you could close this.
