### ISSUE TITLE
not a bug but a suggestion

### ISSUE THREAD

**Issue by artoodeeto** [seanpmaxwell/overnight#31]
hey dude. this is really getting popular. you need to signup here so we can support you.

https://opencollective.com/

thank you! 😄

**Comment by seanpmaxwell** [comment]
wow really. Seems like it shot up then tanked.

**Comment by artoodeeto** [comment]
@seanpmaxwell it will shot up again so prepare. people are moving to typescript and ive recommended this to some of my friends and theyre using this on their personal projects. :smile:

**Comment by seanpmaxwell** [comment]
It was going up to 4000 downloads per week then just flatlined at about 2000 per week. If it goes back up again I might be interested. I'll close this issue for now though. Anyway thanks for the compliments
