### ISSUE TITLE
Can't Import ErrorMiddleware

### ISSUE THREAD

**Issue by db-s** [seanpmaxwell/overnight#38]
I'm trying to import `ErrorMiddleware` but getting the following error -

```
Module '"../../node_modules/@overnightjs/core/lib"' has no exported member 'ErrorMiddleware'.ts(2305)
```

**Comment by seanpmaxwell** [comment]
hmmm, it's working for me. which version are you using. 1.6.12 (the latest) is required for that decorator.

**Comment by seanpmaxwell** [comment]
Any luck, I'd like to close this if that was the issue.

**Comment by db-s** [comment]
It worked after updating the package.
