### ISSUE TITLE
Wrapper does not work when method has more than 3 parameters

### ISSUE THREAD

**Issue by joeykilpatrick** [seanpmaxwell/overnight#42]
I'm not sure if this is a bug or an unimplemented feature. 

Version: `1.6.14`

Clearly if `@Wrapper(...)` is not used on a method, then the method must be of type `(req: Request, res: Response) => any` to work. However, if `@Wrapper(func)` is defined, then the method `method(...)` really could be of any type, as long as `func(method)` is of type  `(req: Request, res: Response) => any`.

Currently, if `method(...)` has up to three parameters, this works. However, if `method(...)` has more than three parameters, then the method returns `null`.

Consider the following:

```typescript
@Controller('path')
export class BigWrapperController {

    @Get('3args')
    @Wrapper(returnAsMessage(1, 1, 1))
    sum3(num1: number, num2: number, num3: number): number {
        return num1 + num2 + num3;
    }

    @Get('4args')
    @Wrapper(returnAsMessage(1, 1, 1, 1))
    sum4(num1: number, num2: number, num3: number, num4: number): number {
        return num1 + num2 + num3 + num4;
    }

}

/**
 * Wrapper that passes its arguments to the method and then handles the
 * request with a 200 status code and the method's return value as a
 * message in the response body.
 * @param args Arguments to be passed to the method
 */
function returnAsMessage(...args: any) {
    return (method: Function): RequestHandler => {
        return (req: Request, res: Response): Response => {
            return res.status(200).json({
                message: method(...args)
            })
        }
    }
}
```

When calling the route `/path/3args`, the response is:
``` typescript
{
    message: 3
}
```
When calling the route `/path/4args`, the response is:
``` typescript
{
    message: null // Should be 4
}
```
Code to reproduce is linked [here](https://gist.github.com/joeykilpatrick/aa16b364421d597e54a433e9184b11c5).

**Comment by jkilpatrick15** [comment]
#41 Closes this issue
