### ISSUE TITLE
controllers does not support multiple method 

### ISSUE THREAD

**Issue by MuBoori** [seanpmaxwell/overnight#46]
If I tried to make route to work on both Post and Get. It does not work either I get @post or @get to work in one time.
> @Post()
> @Get()
>   public async method(req: Reqest, res: Response) {
> }

**Comment by joeykilpatrick** [comment]
#41 Adds this feature

**Comment by seanpmaxwell** [comment]
Why would you want to call the exact same method for both a post and a get?

**Comment by joeykilpatrick** [comment]
Some possible scenarios:
- You want to handle the same custom error for multiple HTTP methods.
``` typescript
@Get('some-deprecated-function')
@Put('some-deprecated-function')
private method(req: Request, res: Response) {
    return res.status(GONE).json({ // Status code 410
        message: 'This resource was removed in version 2.x.x.'
    });
}
```
- You want to handle the same method with multiple routes.
``` typescript
@Get('person/:id')
@Get('id/:id/person')
private get(req: Request, res: Response) {
    // ...
}
```

**Comment by MuBoori** [comment]
Well, I have the same logic to support a return url that can be either GET
or POST so instead of doing two methods with the same logic routing them to
the same method.
As a work around i ve done the below but it would be great if it support
that as i used to work with similar java framework that it work fine with
multiple methods for the same decrotor.

@Get()
Public methodA(){
Return methodB();
}

@Post()
Public methodB(){}

**Comment by seanpmaxwell** [comment]
I went I finished reviewing @joeykilpatrick 's pull request it will contain the feature

**Comment by seanpmaxwell** [comment]
Merged @joeykilpatrick's pull request. Sorry for taking so long.
