### ISSUE TITLE
Working with passport js

### ISSUE THREAD

**Issue by dechans** [seanpmaxwell/overnight#47]
Hi,

I'm looking to integrate passportjs with typescript and overnight js, but it don't work.
Please, do you have or can you do an example with typescript, overnight js and passport (google) integration ?

I'm lost.

Thanks

**Comment by seanpmaxwell** [comment]
I haven't used Passport. I do use GoogleAuth. But I just call the GoogleAuth API from within my API. Can you post a code example?

**Comment by seanpmaxwell** [comment]
Looks to me like Passport is a middleware. You would just add it like you would any other @Middleware decorator or you could in the Serve class using this.app.use(/* passport object */).

**Comment by dechans** [comment]
Yes, you're right, need to use @Middleware(passport.auth....)
Thanks a lot
