### ISSUE TITLE
Add controller prefix option

### ISSUE THREAD

**Issue by AnandChowdhary** [seanpmaxwell/overnight#48]
Would be cool if we could have a global prefix added to all controllers, like this:

```ts
this.app.setPrefix("v1/");
super.addControllers([new UsersController()];
```

Then, the routes can be generated as `/v1/users` instead of `/users`, which can be used for versioning, or having a global `/api` prefix, etc.

**Comment by seanpmaxwell** [comment]
Why not just add create a root level parent controller and add v1 to that?

**Comment by AnandChowdhary** [comment]
I didn't realize that existed, thanks!

**Comment by ivanguimam** [comment]
I have the same problem. Only I'm using [inversify](https://github.com/inversify/InversifyJS) to inject the services into my controllers, so I can't use a parent controller.
