### ISSUE TITLE
Global middleware for async handler

### ISSUE THREAD

**Issue by AnandChowdhary** [seanpmaxwell/overnight#49]
I'm trying to add the async handler (`express-async-handler` as a global middleware, but I'm unable to get it to work and would love some help.

Doing this works:

```ts
import asyncHandler from "express-async-handler";

@Controller("users")
@ClassMiddleware(asyncHandler)
export class UserController {}
```

But doing this doesn't work (because the types of the handler and required ParamsDictionary don't match (Argument of type '(handler: RequestHandler<ParamsDictionary>) => RequestHandler<ParamsDictionary>' is not assignable to parameter of type 'RequestHandler<ParamsDictionary>'):

```ts
super.addControllers([new UsersController()], undefined, asyncHandler);
```

But doing any of the following don't work either, but don't have the TS error:

```ts
super.addControllers([new UsersController()], undefined, () => asyncHandler());
```

```ts
super.addControllers([new UsersController()], undefined, (req, res, next) => asyncHandler(next));
```

When doing this, the error is "Argument of type 'Request<ParamsDictionary, any, any>' is not assignable to parameter of type 'RequestHandler<ParamsDictionary>'.":

```ts
super.addControllers([new UsersController()], undefined, req => asyncHandler(req));
```

I'm sure I'm just doing something silly...

**Comment by seanpmaxwell** [comment]
Looking at express-async-handler docs seems like your supposed to call asyncHandler as the arg and pass it a requesthandler, asyncHandler(requestHandler)

**Comment by AnandChowdhary** [comment]
Thanks! I think I'll explore other ways to do this in my generator to make sure I can use it globally.

**Comment by rnarayana** [comment]
> 
> 
> > Did you figure out a way? I'm exactly at this point.
> 
> @rnarayana, I'm now using a custom-built generator script that injects specific code in every controller on build time. My system also generates controllers based on routes, so `path/to/controller.ts` means the endpoints will be `@Controller("path/to/controller")`.
> 
> It's definitely highly custom and an overkill, and is used in [@staart/api](https://github.com/staart/site). Here's the source: https://github.com/staart/packages/blob/master/packages/scripts/src/commands/controllers.ts#L66

Oh ok. Too much, will just stick it in every class.
