### ISSUE TITLE
Params not available when in controller

### ISSUE THREAD

**Issue by AnandChowdhary** [seanpmaxwell/overnight#51]
In this case:

```ts
@Controller(":id/about")
export class UserController {
  @Get()
  about(req: Request, res: Response) {
    console.log(req.params.id); // undefined
    res.json({ hello: "world" });
  }
}
```

`req.params.id` doesn't exist, because it's not defined in `@Get()` but in `@Controller`.

Is this intentional, or a bug with Express.js or with Overnight?

**Comment by seanpmaxwell** [comment]
Hmm this might be an Overnight bug, let me look into it.

**Comment by seanpmaxwell** [comment]
I think you need to do `@ClassOptions({mergeParams: true})`. I keep forgetting this. It's also required in express. I've had a lot of people post about this issue. Maybe I should update the readme.

**Comment by AnandChowdhary** [comment]
That works, thanks! I didn't know Overnight was using express (sub)routers under the hood, for some reason I always imagined some kind of route concatenation, but that's silly of me.

Yes, perhaps it's a good idea to add the `mergeParams` note in the README section about child controllers. Thanks again!
