### ISSUE TITLE
'Server' no longer exported

### ISSUE THREAD

**Issue by gmaughan** [seanpmaxwell/overnight#59]
After upgrading from v1.7.3 of @overnightjs/core.

My TypeScript import statement:

```
import { Server } from '@overnightjs/core';
```

gives the error: 

> Module '"../node_modules/@overnightjs/core/lib"' has no exported member 'Server'.ts(2305)

Tracing this back to @overnightjs/core/lib/index.d.ts the error is: 

> Could not find a declaration file for module './Server'. '../node_modules/@overnightjs/core/lib/Server.js' implicitly has an 'any' type.ts(7016)

Downgrading to v1.7.2 fixes the issue.

@overnightjs/core: 1.7.3
typescript: ~3.8.3

**Comment by seanpmaxwell** [comment]
let me know if 1.7.4 fixes the issue for you

**Comment by gmaughan** [comment]
Fixed. Thank you. Excellent response time.
