### ISSUE TITLE
ES6+ targeting with overnight decorators 

### ISSUE THREAD

**Issue by orenmizr** [seanpmaxwell/overnight#6]
while node advances in versions - more of the language does not require transformation. i can't seem to get classes to work with es6 target and i don't want to change to es5 to fix it. 
any suggestions ? 

dev mode:  ts-node with debugger

**Comment by seanpmaxwell** [comment]
Hmm, I haven't tried Overnight with es6 at all. If you're using TypeScript what's the importance of the Node version? Generally it's a good idea to transpile to es5 to avoid version issues.

**Comment by orenmizr** [comment]
first, thanks for the reply.

doesn't node ("harmony" ) support most of the it native ?
i figured it would be better performance and debug experience to keep the
code as close to it origin.

**Comment by seanpmaxwell** [comment]
There are no significant performance differences between transpiling to es5 vs es6. As far as debugging, you should do all of that in ts-node before transpiling. With my IDE I can debug ts-node with `node --require ts-node/register start.ts`

**Comment by seanpmaxwell** [comment]
I did a little digging and it looks like Microsoft is recommended to use es6 now. I'll update the project to use es6 instead of es5.

**Comment by chenkang084** [comment]
@seanpmaxwell @orenmizr I have the same issue that typescript compiler's target is `ES2015` looks not work , and i deep dive the root cause looks like the extends logic is different from `es5` since the code `const prototype = controller.__proto__.__proto__;` return a empty array.

**Comment by seanpmaxwell** [comment]
Request has been fulfilled. Sorry it took so long I was on vacation. OvernightJS is now compatible with both es5 and es6.
