### ISSUE TITLE
Make decorators work with arrow functions as well as methods

### ISSUE THREAD

**Issue by nozzlegear** [seanpmaxwell/overnight#8]
Hey! I'm having trouble getting the Overnight path decorators to work with arrow functions (class properties) on a controller class. It works just fine with regular functions, but if we turn them into arrow functions it stops working, even though they still have the exact same signature. There are a couple reasons I want to do this, chiefly so I can easily use my own types for the request and response objects (mostly to get intellisense on `req.app.locals`); but also it helps with `this` binding in some corner cases. 

Here's an example of what I'm trying to do:

```ts
type CustomRequestHandler = (req: CustomRequest, res: CustomResponse) => Promise<void>;

@Overnight.Controller("/something")
export class SomethingController {
    @Overnight.Get("example/1")
    async exampleOne(req: Express.Request, res: Express.Response) {
        // This works
    }

    @Overnight.Get("example/2")
    async exampleTwo(req: CustomRequest, res: CustomResponse) {
        // Also works
    }

    @Overnight.Get("example/3")
    exampleThree: CustomRequestHandler = async (req, res) => {
        // This is what I'm trying to do, but it does not work.
        // Unable to resolve signature of property decorator when called as an expression.
    }

    @Overnight.Get("example/4")
    exampleFour: (req: CustomRequest, res: CustomResponse) => Promise<void> = async (req, res) => {
    // Also does not work
    }
}
```

If I try to use arrow functions, TypeScript gives an error saying `Unable to resolve signature of property decorator when called as an expression`. I'm not super familiar with decorators yet, but I assume this error happens because `@Overnight.Get` is a method decorator, but arrow functions are considered properties. Would it be difficult to get the decorators work with both class methods and class properties?

**Comment by seanpmaxwell** [comment]
Your feature request has been fulfilled. You can now create routes with arrow functions. Sorry it took so long is was on vacation. You can do it like this:

```
    @(OvernightJS as any).Get('arrow/:id')
    private get = (req: Request, res: Response) => {
        this.logger.info(req.params.id);
        return res.status(200).json({msg: 'get_arrow_called'});
    }
```

**Comment by nozzlegear** [comment]
Cool, thank you very much!

--
Josh Harms

**Comment by seanpmaxwell** [comment]
Please star the repo if you have not yet.
