### ISSUE TITLE
Add possibility to wrap routes in try catch

### ISSUE THREAD

**Issue by BennoDev** [seanpmaxwell/overnight#9]
OvernightJS can currently not handle errors happening in asynchronous function calls and will throw `UnhandledPromiseRejectionWarning` if the execution of this function is not wrapped in a `try/catch` block. 

Having to wrap every controller method in a try catch is repetition and clutter for the code though, it could be a good idea to implement, or atleast find a way to support a typical 'handle async' wrapper function for controller methods.

Wrapping controller methods (or providing an option to wrap them) into [something like this](https://github.com/icapps/tree-house/blob/master/src/lib/responder.ts) at router creation time would fix this issue.

**Comment by seanpmaxwell** [comment]
well you could add a different router as a middleware such as express-promise-router. Then do something like this:

```
    @Get(':id')
    private get(req: Request, res: Response): Promise<Response> {
        return this.someAsyncFunction(req.params.id)
                    .then(ret => res.status(200).json({msg: ret}));
    }
```

I gave that example in the readme cause I know some aren't big fans of using try/catch blocks.

**Comment by AnandChowdhary** [comment]
Can we reopen this issue?

I'd love to explore the option to provide a wrapper function for every method.

Like we have `@ClassMiddleware`, we can have a `@ClassWrapper` and `@Wrapper`:

```ts
const asyncWrapper = (action: (request: Request, response: Response, next?: NextFunction) => any), next: NextFunction) => {
    try {
       return await action(request, response, next);
    } catch (error) {
        next(error);
    }
}

@Controller("api/users")
@ClassWrapper(asyncWrapper)
export class UserController {
    @Get(":id")
    async get(req: Request, res: Response) {
        res.json({ user: req.params.id });
    }
}
```

This makes it consistent with the [express-async-handler](https://github.com/Abazhenov/express-async-handler) approach which is very useful in async functions.

**Comment by seanpmaxwell** [comment]
Working on it now. Will let you know when that decorator is finished. Thank you for the tips on how to make Overnight better. I don't know if we can do a @ClassWrapper but we could definitely do a @Wrapper for methods.

**Comment by seanpmaxwell** [comment]
Your feature request has been fulfilled. Please checkout the readme and look at the `@Wrapper` and `@ClassWrapper` decorators.

**Comment by AnandChowdhary** [comment]
This is absolutely amazing. Thank you so much!

One quick thought: Most of times, if you’re using asynchronous functions, you’d want to wrap everything in the handler.

What do you think about having a super.addWrapper just like addController which is even one level above @ClassWrapper? This would also eliminate the need to duplicate the async wrapper in each controller. :)

**Comment by seanpmaxwell** [comment]
Wouldn't it be better just to use a different router at that point like express-promise-router?

**Comment by AnandChowdhary** [comment]
Any chance I can bother you again to share an example of `express-promise-router`? I haven't been able to make it work with Overnight using the example in README or otherwise.

**Comment by seanpmaxwell** [comment]
Oh really. Is the example in the sample project not working?

https://github.com/seanpmaxwell/overnight/blob/master/sample-project/src/controllers/CustomRouterController.ts

https://github.com/seanpmaxwell/overnight/blob/master/sample-project/src/CustomRouterServer.ts
