### ISSUE TITLE
Is this repository deprecated?

### ISSUE THREAD

**Issue by victorhnogueira** [seanpmaxwell/overnight#99]
This repository has not been accepting new PR for some time. @seanpmaxwell is this repository deprecated?

**Comment by seanpmaxwell** [comment]
Yeah, this seems to be a better library: `routing-controllers`

**Comment by VersusF** [comment]
Thanks for the reply. Maybe this should be mentioned in the Readme...

**Comment by jondot** [comment]
I actually really like this repo, thanks Sean!
I’ve forked it and applied some upgrades, it is about to be open source as part of https://hyperstackjs.io
